@DotnetAPI_HostAddress = http://localhost:5023

###
GET {{DotnetAPI_HostAddress}}/api/articles?page=1&pageSize=10
Accept: application/json


###
GET {{DotnetAPI_HostAddress}}/api/articles/1
Accept: application/json

###
